---
title: "sprites-load-timing"
author: "Benoît Beraud & Alexandre Masselot"
date: "4 December 2015"
output: pdf_document
---

With Benoit blog post. Displayload timings

```{r,fig.width=8.5,fig.height=5}
library(ggplot2)
df = read.csv('data/sprites-summary.csv')
df$setup = factor(df$setup, levels = c("individual-10%", "individual-30%",
                                       "individual-50%",  "individual-80%",
                                       "individual-100%", "sprite set"))
df.no.sprites = df[df$setup != 'sprite set',]
df.conf3 = df[df$configuration == 3,]
df.conf3.no.sprites = df[df$setup != 'sprite set' & df$configuration == 3,]

graph1 = ggplot(df, aes(x=setup, y=load.time)) +
     geom_point(aes(colour=protocol, shape=browser),
                size=2,
                alpha=0.9,
                position = position_jitter(w=0.05, h=0)
                ) +
     scale_colour_manual(values = c('blue', 'red')) +
     facet_wrap(~network, ncol = 1, scales = 'free_y') +
      theme_bw() +
      theme(axis.text.x=element_text(angle = 30, hjust = 1),
            plot.title = element_text(vjust=2)) +
      geom_smooth(data=df.no.sprites,
                  aes(x=setup,
                      y=load.time,
                      group=interaction(browser, protocol),
                      colour=protocol,
                      linetype=browser
                      ),
                  method='lm',
                  formula= y~x,
                  se=FALSE,
                  alpha=0.7
                  ) +
      labs(title='Images loading time versus arrangement, browser and protocol',
         y='loading time (s)',
         x='image arrangement'
         ) 


print(graph1)

```

```{r, fig.width = 9, fig.height = 4}
graph2 = ggplot(df.conf3, aes(x=X..of.images, y=load.time)) +
     geom_point(aes(colour=protocol, shape=browser),
                size=2,
                alpha=0.9,
                position = position_jitter(w=0.05, h=0)
                ) +
     scale_colour_manual(values = c('blue', 'red')) +
      theme_bw() +
      theme(axis.text.x=element_text(angle = 30, hjust = 1),
            plot.title = element_text(vjust=2)) +
      geom_smooth(data=df.conf3.no.sprites,
                  aes(x=X..of.images,
                      y=load.time,
                      group=interaction(browser, protocol),
                      colour=protocol,
                      linetype=browser
                      ),
                  method='lm',
                  formula= y~x,
                  se=FALSE,
                  alpha=0.7
                  ) +
      labs(title='Images loading time versus number of images, browser and protocol',
         y='loading time (s)',
         x='number of images'
         ) 


print(graph2)

```

```{r, fig.width = 9, fig.height = 4}
graph3 = ggplot(df.conf3, aes(x=Total.size, y=load.time)) +
     geom_point(aes(colour=protocol, shape=browser),
                size=2,
                alpha=0.9,
                position = position_jitter(w=0.05, h=0)
                ) +
     scale_colour_manual(values = c('blue', 'red')) +
      theme_bw() +
      theme(axis.text.x=element_text(angle = 30, hjust = 1),
            plot.title = element_text(vjust=2)) +
      geom_smooth(data=df.conf3.no.sprites,
                  aes(x=Total.size,
                      y=load.time,
                      group=interaction(browser, protocol),
                      colour=protocol,
                      linetype=browser
                      ),
                  method='lm',
                  formula= y~x,
                  se=FALSE,
                  alpha=0.7
                  ) +
      labs(title='Images loading time versus images total size, browser and protocol',
         y='loading time (s)',
         x='images total size (kB)'
         ) 


print(graph3)


dis = read.csv('data/sprites-distribution.csv')


```

```{r, fig.width = 9, fig.height = 4}
graph4 = ggplot(dis, aes(x=Data, y=Prctile)) +
     geom_point(size=2,
                alpha=0.9,
                color = 'blue'
                ) +
      theme_bw() +
      theme(axis.text.x=element_text(angle = 30, hjust = 1),
            plot.title = element_text(vjust=2)) +
      labs(title='Distribution of image loading time',
         x='loading time (s)',
         y='percentile'
         ) 


print(graph4)

```


